grafana:
  service:
    type: NodePort
    nodePort: 30300
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi

prometheus:
  service:
    type: NodePort
    nodePort: 30090
  prometheusSpec:
    retention: 6h
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    storageSpec: {}

alertmanager:
  service:
    type: NodePort
    nodePort: 30903
  alertmanagerSpec:
    resources:
      requests:
        cpu: 25m
        memory: 64Mi

kubeStateMetrics:
  enabled: true
nodeExporter:
  enabled: true
